# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-pussh" do
  desc "Upload Docker images to remote servers via SSH without an external registry."
  homepage "https://github.com/psviderski/unregistry"
  version "0.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pussh"

  on_macos do
    on_intel do
      url "https://github.com/tonyo/unregistry/releases/download/v0.0.13/unregistry_0.0.13_darwin_amd64.tar.gz"
      sha256 "c4f33005493a102a451a205861fdf7e4826969a3276bbd870afc68d6a02f2abd"
    end
    on_arm do
      url "https://github.com/tonyo/unregistry/releases/download/v0.0.13/unregistry_0.0.13_darwin_arm64.tar.gz"
      sha256 "c4f33005493a102a451a205861fdf7e4826969a3276bbd870afc68d6a02f2abd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonyo/unregistry/releases/download/v0.0.13/unregistry_0.0.13_linux_amd64.tar.gz"
      sha256 "c4f33005493a102a451a205861fdf7e4826969a3276bbd870afc68d6a02f2abd"
    end
    on_arm do
      url "https://github.com/tonyo/unregistry/releases/download/v0.0.13/unregistry_0.0.13_linux_arm64.tar.gz"
      sha256 "c4f33005493a102a451a205861fdf7e4826969a3276bbd870afc68d6a02f2abd"
    end
  end

  def caveats
    <<~EOS
      To use docker-pussh as a Docker CLI plugin ('docker pussh' command) you need to create a symlink:

        mkdir -p ~/.docker/cli-plugins
        ln -sf #{opt_bin}/docker-pussh ~/.docker/cli-plugins/docker-pussh

      After installation, you can use it with:
        docker pussh [OPTIONS] IMAGE[:TAG] [USER@]HOST[:PORT]

      To uninstall the plugin:
        rm ~/.docker/cli-plugins/docker-pussh
    EOS
  end

  test do
    # Test the command output with no arguments.
    assert_match "IMAGE and HOST are required", shell_output("#{bin}/docker-pussh 2>&1", 1)
  end

  # No zap stanza required
end
